version: '3.4'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
        - 3306:${DB_PORT}
    volumes:
      - ./db:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    command: mysqld --sql_mode=""

  phpmyadmin:
    image: phpmyadmin:5.2.0
    restart: always
    ports:
      - 3000:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

